export const ALL_PROJECT_REQUEST = "ALL_PRODUCT_REQUEST";
export const ALL_PROJECT_SUCCESS = "ALL_PRODUCT_SUCCESS";
export const ALL_PROJECT_FAIL = "ALL_PRODUCT_FAIL";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
